### ISSUE TITLE
Research a way to get OSM files of a specific area/city upon demand

### ISSUE THREAD

**Issue by carocad** [n7a235/README#15]
As you know, in order for us to provide routing to user we need (at least !! ) two sources of information:
- OSM files to get a graph representation of the real world road network
- GTFS files or similar to get information about the routes, stations and timetables of the transport network

This issue is only about the OSM files. Currently we only have one for the Saarland Bundesland. We need to find a way to get OSM files on demand of a specific region of interest. Such that if today we want an OSM file for Frankfurt and tomorrow we want one for Freiburg it should be equally possible with a simple script.

So far I know that OSM has several API to get information but I havent found a way to get them. It is not necessary for this to be automated. I think that would be a second step. For now it would suffice to know which API to use (from a browser for example) and with which parameters

http://wiki.openstreetmap.org/wiki/Databases_and_data_access_APIs

**Comment by carocad** [comment]
@mehdisadeghi any advance in this front?

**Comment by mehdisadeghi** [comment]
@carocad according the the link above every week a dump of all OSM files are available and every hour there are change sets for updates. Since we can't download and maintain the whole data at the moment we have to prioritize things. Which regions are of interest now?

**Comment by carocad** [comment]
@mehdisadeghi I would say Frankfurt, Freiburg and Cologn. The first two are for us to test locally and the third is because they published some gtfs files which we could use to test the bus routing.

**Comment by mehdisadeghi** [comment]
Defining the boundaries of a region we can use Overpass API instances to download OSM data in XML format. Try [this](http://overpass-api.de/api/map?bbox=11.54,48.14,11.543,48.145). Nevertheless, I'm looking at similar APIs.

**Comment by carocad** [comment]
@mehdisadeghi that is great to know !

I am currently using the boundaries that Mapbox returns for geocoding. They return the bbox of the wrapping "context" in increasing order. For example: neighbourhood, city, bundesland, country.

Reference: https://www.mapbox.com/api-documentation/#response-object

**Comment by mehdisadeghi** [comment]
Another option is downloading per-city OSM data from [geofabrik](http://download.geofabrik.de/europe/germany.html). This one apparently has already downloaded and separated data for each city, including Saarland, Hessen, Berlin (and Brandenburg) and Baden-Würrtemberg (including Freiburg), all with bz2 files ready to download.

**Comment by mehdisadeghi** [comment]
@carocad I'd assume  _Overpass API_ and _geofabrik_ are the solution for this issue. Therefore I'll close this, feel free to reopen if you have anything else in mind.
