### ISSUE TITLE
geocoding engine selection

### ISSUE THREAD

**Issue by carocad** [n7a235/README#6]
Through the mapbox sdk we can search for places and other related information. Nevertheless mapbox doesnt provide direct information of the place. [1]

They provide, though, a Wikidata [2] id from which we could get the information.

The problem is that obviously there is no complete source of information in the world. So we can not assume that all places are going to be in Open street maps nor that all places will have a wikidata id to get information from.

Other alternatives sources are Google Places [3] and Facebook [4] but of course this sources are proprietary. In that sense this problem becomes a bit more subjective since it concerns:
- where do we get the information?
- who do we trust?
- what do we do if we find a place but no associated description (for example a place in OSM without a wikidata id)?

On the other hand is the monetary problem. Both Facebook and Google offer their services with a free tier up until one point. Wikidata also offers that but (in my opinion) it lacks lots of places since things like restaurants, cafes and similar are not so important to put there.

References:
- [1] https://www.mapbox.com/api-documentation/#response-format
- [2] https://www.wikidata.org/wiki/Q1622133
       https://www.wikidata.org/wiki/Special:EntityData/Q1622133.json
- [3] https://developers.google.com/places/?hl=es
- [4] https://developers.facebook.com/products/places

**Comment by carocad** [comment]
yelp, could also be another alternative (and they already use graphql :) )
- https://www.yelp.com/developers/graphql/guides/intro

**Comment by mehdisadeghi** [comment]
> Other alternatives sources are Google Places [3] and Facebook [4] but of course this sources are proprietary.

I think (and it seems obvious) that the information here is part of their "assets". They can sell services on top of them and optimize other ones or create entirely new ones. 

> where do we get the information?

To be sustainable in long run, one must eat their own dog food. In short term, paid services, free tiers, public data, API for transport companies, interpolated info from other sources, etc.

> who do we trust?

What do you mean by trust? Data accuracy? I think we shouldn't build anything on trust, but on some measures. If data is inaccurate we have to discard it, if a source is providing out of date data, we have to change it.

> what do we do if we find a place but no associated description (for example a place in OSM without a wikidata id)?

Do we need to search for places or we should better focus on stations only?

**Comment by mehdisadeghi** [comment]
> yelp, could also be another alternative (and they already use graphql :) )

I read their GraphQL article. It is straight forward. However, they provide business information, how are we supposed to use their info in routing?

**Comment by carocad** [comment]
> Do we need to search for places or we should better focus on stations only?

I see searching for places and addresses as a must for a complete routing system. A user's destination are often not its final stop but rather a place that that person wants to visit. For example: you want to go to the concert hall on a weekend, but you have never been there. How are you suppose to know the name of the station if you dont know the surroundings? On the other hand, simply entering the address and letting the routing engine handle it for you is way more convenient.

> I read their GraphQL article. It is straight forward. However, they provide business information, how are we supposed to use their info in routing?

Sorry for this. I mixed up two topics. One if `geocoding` and the other one is `place metadata`. Lets discard the `metadata` one and focus on the `geocoding`.

For a general routing service we need a way to relate the user goal  (place, address) to a representation that our servers can understand. In general that means a mapping from place/address to latitude,longitude. In general that is what geocoding does. Nevertheless the world representation that we have on the servers might have different information (due to an outdatted geocoding service, error on our side, etc). Therefore we need to use those coordinates and find the closest point in our database to the one provided.

The point here is that the address/place to coordinates needs to take place somewhere, hopefully not on our servers otherwise this gets even more complicated. Therefore I am currently using Mapbox geocoding service but through several tests I have found out that its performance might not be as good. So maybe we should consider using another geocoding service or providing a fallback when one fails (which was actually my initial thought)

**Comment by carocad** [comment]
So for the record (and to keep @mehdisadeghi  in the loop). I will follow the strategy that I mentioned in this issue: https://github.com/mapbox/carmen/issues/639

Basically using mapbox api as starting point and using photon.koomot as fallback if the previous fails.

I still need to do implement it in the app but it should be straigthforward :)

**Comment by carocad** [comment]
this was solved in 21b5796eccca20c703fdb5d7217c89e6abbf0baf. We use [photon](https://photon.komoot.de/) geocoding engine as fallback whenever mapbox doesnt not return any result for a user input
