### ISSUE TITLE
Evaluate and implement a DB crawler

### ISSUE THREAD

**Issue by carocad** [n7a235/README#7]
Base on our last conversation I think this project would suit you quite well to get yourself started. You would have to start it from scratch and develop it based on your own design and decisions.

The idea is to evaluate and (if deemed necessary) create a Deutsche Bahn crawler which would crawl the information published by the DB and output it in a format which we could use for our app. 

Right now I can think of the following questions/constraints:
- how much information can we get from DB?
- are we free to use it however we want or are there restrictions?
- should the crawling results be available live or only on batches? (every 5 or 15 minutes for example)
- who would be responsible for crawling the information, the client or our server?
- should we completely rely on their information or rather use their information in conjunction with our own knowledge base?
- use a format that can be understood by both client and servers (geojson/GTFS ?)

Depending on your results and decisions I will decide if I continue working on the mobile app or if I rather go with the route editor #5 

Let me know your thoughts on this.

References:
- http://data.deutschebahn.com/dataset/api-fahrplan
- http://geojson.org/
- https://firebase.googleblog.com/2017/03/how-to-schedule-cron-jobs-with-cloud.html
- https://developers.google.com/transit/gtfs/

**Comment by mehdisadeghi** [comment]
> how much information can we get from DB?

[DB Open Data Portal](data.deutschebahn.com) provides multiple data-sets each with its own license and conditions. Hier is a general quote from their portal:

> Die Daten stehen zur freien Verwendung und Weiterverwertung, in maschinenlesbarer und offen lizenzierter Form, in unterschiedlichen Formaten, dauerhaft und kostenlos zur Verfügung.

They have at the moment 27 datasets available to download and 9 different datasets which are available via API calls. Their [developer portal](developer.deutschebahn.com) lists 11 APIs however. Each API has its own limitation. For example StationData has a limit of 100 API calls per minute. Some APIs support unlimited calls, such as Fahrplan API. (It is possible to try API calls using Swagger ui in developer portal).

> are we free to use it however we want or are there restrictions?
See above. They are mostly free to use with licenses such as CC BY 4.0.

> should the crawling results be available live or only on batches? (every 5 or 15 minutes for example)

At least with DB crawling does not make much sense. Datasets are updated yearly or so and we don't need realtime data for now.

> who would be responsible for crawling the information, the client or our server?

I would say definitely the server. This is a batch job. However, there are [repositories](https://github.com/fredlockheed/db-fv-gtfs) already dedicated to collect this information that we can use.

> should we completely rely on their information or rather use their information in conjunction with our own knowledge base?

It depends. They have done quite good job in opening their data along with necessary API which is good. However, if we can't get necessary information out of it we might need to find other sources. I will put some info on travic separately.

> use a format that can be understood by both client and servers (geojson/GTFS ?)

Their API returns mostly JSON. They have Datasets in CSV, XLSX, GeoJSON and even PDF. But more interesting ones are available via API.

**Comment by carocad** [comment]
@mehdisadeghi parsing a GTFS file is extremely easy in Clojure. I actually did that [in my thesis](https://github.com/n7a235/backend.functions.hypobus/blob/dev/test/hypobus/simulation/data_handler.clj#L58) to compare the results against published data and found out the published data was wrong :/

Anyway I would say, lets start with the already published GTFS data and see how far we can go with that. I think for a prototype it is more than enough. Later on we should add more sources and complete the transport network with it.

I think it would be a good exercise for you to parse the GTFS file and extract the information that we want. The only gtfs-related function that I created was the [raw-shapes](https://github.com/n7a235/backend.functions.hypobus/blob/dev/test/hypobus/simulation/data_handler.clj#L60) which simply extracted the curves from the gtfs files.

For routing, nevertheless we are more interested in the stations and lines. I think we can safely ignore the time-table for now and introduce it later on.

PS: the first two links of your previous post are broken.

**Comment by carocad** [comment]
@mehdisadeghi what is your veredict here? Do we need this or can we rely on the GTFS files that we can find online?

**Comment by mehdisadeghi** [comment]
I think at the moment we don't need a crawler, since there is nothing that we can get with it. As discussed in the [other issue](https://github.com/n7a235/README/issues/14#issuecomment-314758681) we are limited to a number of options listed there, unless we grow enough and convince them to get us more data or use a university contract that allows us to obtain the necessary data.

So I'll close this issue, feel free to reopen if you think we still need a crawler.
